# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """\
$directory $all$fill$cmd_duration$line_break\
$username$hostname $character\
"""


# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold #92F779)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold #FF8282)'

[username]
style_user = '#ffbebc bold'
style_root = 'red bold'
format = "[$user]($style)"
show_always=true

[username.aliases]
"Administrator" = "root"

[hostname]
ssh_only = false
style = "white dimmed"
format = "@[$ssh_symbol$hostname]($style)"

[directory]
use_os_path_sep=false
style = "white bold"
format="[ $path]($style)[$read_only]($read_only_style)"
truncate_to_repo=false
truncation_length=-1

[git_branch]
style = "bold #E37BBC"


[nodejs]
style = "bold #3FE054"

[cmd_duration]
min_time = 0
style = "#855cff bold"
format = ' [$duration]($style)'
disabled = false
show_notifications = false
min_time_to_notify = 10_000

[git_status]
modified = "*"
style = "#ffa545 bold"
format = '([\[$all_status$ahead_behind\]]($style) )'
